[package]
name = "media-controller"
version = "0.1.0"
edition = "2021"
authors = ["Nuno David <email@ndavd.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs2 = "0.4.3"
gtk = "0.18.1"
